.TH AUREATE 1 "30 March 2023" "https://swindlesmccoop.xyz"
.SH NAME
AUReate \- a minimalist AUR helper written in C
.SH SYNOPSIS
.B aureate
\fI[ -S, -Ss, -R, -h ]\fP \fI[package]\fP
.SH DESCRIPTION
.B aureate
will read the argument given and adjust its behavior accordingly.
.SH ARGUMENTS
.TP
.IP \fI-S\fP
Build \fI[package]\fP from the AUR.
.IP \fI-Ss\fP
Search the AUR for packages with names containing \fI[package]\fP.
.IP \fI-h\fP
Print a help message with a quick synopsis on what each option does.
.IP \fI-R\fp
Uninstall \fI[package]\fP.
.SH AUTHORS
\fIaureate\fP was written by Swindles McCoop.\fP
